name: Fortify ScanCentral SAST Scan
on: [workflow_dispatch]


jobs:                                                  
  Fortify-SAST:
    # Use the appropriate runner for building your source code
    runs-on: ubuntu-latest 

    steps:
      # Check out source code
      - name: Check Out Source Code
        uses: actions/checkout@v2
   
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      ### Set up Fortify ScanCentral Client ###
      - name: Download Fortify ScanCentral Client
        uses: fortify/gha-setup-scancentral-client@v1   
        with:
          version: 20.2.0                                      # Optional as 20.2.0 is the default
          client-auth-token: CHANGEME321!  # Optional, but required if ScanCentral Controller requires client authentication

      ### Run Fortify ScanCentral Client ###
      # Update BUILD_OPTS based on the ScanCentral Client documentation and your project's included tech stack(s).
      #   ScanCentral Client will download dependencies for maven, gradle and msbuild projects.
      #   For other build tools, add your build commands to the workflow to download necessary dependencies and prepare according to Fortify SCA documentation.
      - name: Perform SAST Scan
        run: scancentral -url http://211.24.79.232:8081/scancentral-ctrl start $BUILD_OPTS -bt none -upload -application Demo -version 3 -uptoken 4f63e2db-0117-45b2-bf1a-135279f19c3e -scan 
           ### Archive ScanCentral Client logs on failure ###
      - name: Save ScanCentral Logs
        uses: actions/upload-artifact@v2                
        if: failure()
        with:
           name: scancentral-logs
           path: ~/.fortify/scancentral/log
